build:
  image: drone/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - GOPATH=$(pwd) go get github.com/stretchr/testify/assert
    - GOPATH=$(pwd) go test maze
    - GOPATH=$(pwd) go build
